package com.example.sportstats.network

import com.squareup.moshi.Json

data class Team(
    val idTeam: String,
    val idSoccerXML: String? = null,
    @Json(name = "idAPIfootball") val idApiFootball: String? = null,
    val intLoved: String? = null,
    val strTeam: String? = null,
    val strTeamShort: String? = null,
    val strAlternate: String? = null,
    val intFormedYear: String? = null,
    val strSport: String? = null,
    val strLeague: String? = null,
    val idLeague: String? = null,
    val strLeague2: String? = null,
    val idLeague2: String? = null,
    val strLeague3: String? = null,
    val idLeague3: String? = null,
    val strLeague4: String? = null,
    val idLeague4: String? = null,
    val strLeague5: String? = null,
    val idLeague5: String? = null,
    val strLeague6: String? = null,
    val idLeague6: String? = null,
    val strLeague7: String? = null,
    val idLeague7: String? = null,
    val strDivision: String? = null,
    val strManager: String? = null,
    val strStadium: String? = null,
    val strKeywords: String? = null,
    val strRSS: String? = null,
    @Json(name = "strStadiumThumb") val strStadiumThumbUrl: String? = null,
    @Transient val strStadiumDescription: String? = null,
    @Transient val strStadiumLocation: String? = null,
    @Transient val intStadiumCapacity: String? = null,
    @Json(name = "strWebsite") val strWebsiteUrl: String? = null,
    @Json(name = "strFacebook") val strFacebookUrl: String? = null,
    @Json(name = "strTwitter") val strTwitterUrl: String? = null,
    @Json(name = "strInstagram") val strInstagramUrl: String? = null,
    val strDescriptionEN: String? = null,
    @Transient val strDescriptionDE: String? = null,
    @Transient val strDescriptionFR: String? = null,
    @Transient val strDescriptionCN: String? = null,
    @Transient val strDescriptionIT: String? = null,
    @Transient val strDescriptionJP: String? = null,
    @Transient val strDescriptionRU: String? = null,
    @Transient val strDescriptionES: String? = null,
    @Transient val strDescriptionPT: String? = null,
    @Transient val strDescriptionSE: String? = null,
    @Transient val strDescriptionNL: String? = null,
    @Transient val strDescriptionHU: String? = null,
    @Transient val strDescriptionNO: String? = null,
    @Transient val strDescriptionIL: String? = null,
    @Transient val strDescriptionPL: String? = null,
    val strGender: String? = null,
    val strCountry: String? = null,
    @Json(name = "strTeamBadge") val strTeamBadgeUrl: String? = null,
    @Json(name = "strTeamJersey") val strTeamJerseyUrl: String? = null,
    @Json(name = "strTeamLogo") val strTeamLogoUrl: String? = null,
    @Json(name = "strTeamFanart1") val strTeamFanArtUrl1: String? = null,
    @Json(name = "strTeamFanart2") val strTeamFanArtUrl2: String? = null,
    @Json(name = "strTeamFanart3") val strTeamFanArtUrl3: String? = null,
    @Json(name = "strTeamFanart4") val strTeamFanArtUrl4: String? = null,
    @Json(name = "strTeamBanner") val strTeamBannerUrl: String? = null,
    @Json(name = "strYoutube") val strYoutubeUrl: String? = null,
    val strLocked: String? = null
)

data class Teams(
    val teams: List<Team>?
)